### ISSUE TITLE
Run-time error with gfortran - solution

### ISSUE THREAD

**Issue by arjenmarkus** [WarrenWeckesser/dde_solver#1] opened 2022-01-15 11:37 UTC
I tried to build and run the examples using gfortran 10.2, but this resulted in a run-time error. Some investigation showed that the problem was at line 6274: the variable MY_TRIM_FREQUENCY was zero. I came up with a simple fix:
`    ! Trim the solution queue.`
`    IF (NSTEPS>0 .AND. MY_TRIM_FREQUENCY > 0) THEN`
`       IF ( MY_MAX_DELAY> 0.0D0 .AND. & `
`           (NSTEPS/MY_TRIM_FREQUENCY)*MY_TRIM_FREQUENCY==NSTEPS) THEN`
`          CALL TRIM_QUEUE(TRIM_GET)`  
`          IQUEUE = MYIPOINT(2)`
`       END IF`
`    END IF`

Another thing: the examples open a file at unit number 6 to write the results to, but gfortran uses that unit also for the print statement. So after the opening of the file all output intended for the screen is going to the file. (This is not a problem with Intel oneAPI Fortran)

**Comment by WarrenWeckesser** [comment] 2022-02-08 18:30
@arjenmarkus, a belated *"Thanks!"* for looking into this.

After a long hiatus, I'm looking into updating dde_solver to fix some issues.  It looks like it works with gfortran 8, but newer versions of gfortran result in crashes of various kinds.  The exact error depends on which version of gfortran is used.

**Comment by arjenmarkus** [comment] 2022-02-08 18:39
YW, I am interested in the package (mostly for intellectual reasons, as I do not have much use for DDEs in my daily work). Is there something I can try and help out with? Your mentioning different errors with different versions of gfortran indicate such mundane errors as array bound violations and uninitialised variables. Have you tried against valgrind?

**Comment by WarrenWeckesser** [comment] 2022-02-08 19:17
I just pushed a commit with your suggested fix for the `MY_TRIM_FREQUENCY` issue.  That was one of the issues that I noticed, so thanks again!

Thanks also for the offer to help--I'll probably take you up on that.  I'll ping you when I have a reproducible problem.

P.S.  Before I order a copy of your Fortran book--is there an imminent new edition that I should wait for?

**Comment by arjenmarkus** [comment] 2022-02-09 07:50
It is an intriguing thought to work on a second edition, but I have no
plans at this moment and so nothing is imminent. You know there is a lot of
activity concerning Fortran and especially the (language) tools that should
come with it? See https://fortran-lang.discourse.group/.

Op di 8 feb. 2022 om 20:17 schreef Warren Weckesser <
***@***.***>:

**Comment by WarrenWeckesser** [comment] 2022-02-12 16:05
> Another thing: the examples open a file at unit number 6 to write the results to...

Fixed in https://github.com/WarrenWeckesser/dde_solver/commit/f05921da11681c4613f8986ff99e19d3240db33c

**Closed as completed by WarrenWeckesser** 2022-02-12 16:06 UTC
